### ISSUE TITLE
Unit Test Fails

### ISSUE THREAD

**Issue by awe2** [uiucsn/astro_ghost#19]
Input:
```python
from astropy import units as u
from astropy.coordinates import SkyCoord
from astroquery.ipac.ned import Ned
c = SkyCoord(ra=185.7288750*u.degree, dec=15.82230*u.degree, frame='icrs')
result_table = Ned.query_region(c, radius=(2/3600)*u.deg, equinox='J2000.0')
```
Fails with:
```python
Traceback (most recent call last):
  File "/people/enge625/.local/lib/python3.9/site-packages/astroquery/ipac/ned/core.py", line 704, in _parse_result
    first_table = votable.parse(tf, verify='warn').get_first_table()
  File "/people/enge625/.local/lib/python3.9/site-packages/astropy/utils/decorators.py", line 604, in wrapper
    return function(*args, **kwargs)
  File "/people/enge625/.local/lib/python3.9/site-packages/astropy/io/votable/table.py", line 177, in parse
    return tree.VOTableFile(config=config, pos=(1, 1)).parse(iterator, config)
  File "/people/enge625/.local/lib/python3.9/site-packages/astropy/io/votable/tree.py", line 3858, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/people/enge625/.local/lib/python3.9/site-packages/astroquery/ipac/ned/core.py", line 144, in query_region
    result = self._parse_result(response, verbose=verbose)
  File "/people/enge625/.local/lib/python3.9/site-packages/astroquery/ipac/ned/core.py", line 708, in _parse_result
    (is_valid, err_msg) = _check_ned_valid(response.content)
  File "/people/enge625/.local/lib/python3.9/site-packages/astroquery/ipac/ned/core.py", line 749, in _check_ned_valid
    strdom = parseString(string)
  File "/people/enge625/.conda/envs/torch2.0.0/lib/python3.9/xml/dom/minidom.py", line 1998, in parseString
    return expatbuilder.parseString(string)
  File "/people/enge625/.conda/envs/torch2.0.0/lib/python3.9/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/people/enge625/.conda/envs/torch2.0.0/lib/python3.9/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 49
```

**Comment by alexandergagliano** [comment]
Closing now, sounds like the asynchronous query solves this! This'll be pushed to a new version shortly.
