### ISSUE TITLE
Pandas Error/ Result of 400 object run

### ISSUE THREAD

**Issue by awe2** [uiucsn/astro_ghost#22]
Howdy Alex, unfortunately the 400 run crashed, I dont have access to the std out

With version:

```python
>>>astro_ghost.__version__
'2.0.7'
```
here is some of stdout:
```python
Adding 43 sources from GLADE back into the catalog...
Warning! Host of ZTF18acbyyff is the hierarchical child of another object in Simbad, choosing parent as host instead...
        main_id otype         ra        dec     dist  membership     cluster
0  LEDA  899446     G  29.483393 -16.335701  0.00016         100  SN 2018huz
Warning! Host of ZTF18acbvgtu is the hierarchical child of another object in Simbad, choosing parent as host instead...
               main_id otype         ra       dec      dist  membership                  cluster
0        MCG-02-07-072   GiG  40.639287 -9.467765  0.000020         100             ZTF18acbvgtu
1  [T2015] nest 201514   PaG  40.831330 -9.460320  0.189594          75  6dFGS gJ024233.4-092804
2   [CHM2007] LDC  184   GrG  40.765000 -8.497778  0.977901         100  2MASX J02423343-0928040
Warning! Host of ZTF20acounxo is the hierarchical child of another object in Simbad, choosing parent as host instead...
               main_id otype          ra       dec      dist  membership                       cluster
0       [TKK2018] 3936   PaG  178.444390 -5.297180  0.129614          75  Gaia DR3 3599062820296650752
1  [T2015] nest 100517   GrG  178.297500 -5.239700  0.170784         100       6dFGS gJ115348.7-051004
2   [CHM2007] LDC  845   GrG  178.130417 -5.538611  0.490575         100  Gaia DR3 3599062820296650752
3          NOGG H  571   GrG  178.132917 -5.637778  0.567821         100  Gaia DR3 3599062820296650752
Warning! Host of ZTF21abbzcxe is the hierarchical child of another object in Simbad, choosing parent as host instead...
              main_id otype          ra       dec      dist  membership                       cluster
0  [ZS2020] cCGs-1456   CGG  217.059800 -1.956000  0.026995         100  Gaia DR2 3649454743866864512
1      [TTG2014] 7526   GrG  217.000968 -1.810272  0.183715         100          UZC J142815.6-015859
2         2PIGG n1597   GrG  216.280208 -1.532833  0.904116         100  Gaia DR2 3649454743866864512
Warning! Host of ZTF20abptxls is the hierarchical child of another object in Simbad, choosing parent as host instead...
          main_id otype         ra       dec      dist  membership                       cluster
0  [TSK2008] 2061   GrG  21.163811 -1.077924  2.728012         100  Gaia DR3 2532065160101908224
Warning! Host of ZTF20acwyoxc is the hierarchical child of another object in Simbad, choosing parent as host instead...
         main_id otype          ra       dec      dist  membership                       cluster
0  SDSSCGB 58915   CGG  159.716667 -0.936944  0.009225          75  Gaia DR3 3805942049094993408
Warning! Host of ZTF20acwfcfs is the hierarchical child of another object in Simbad, choosing parent as host instead...
           main_id otype          ra       dec      dist  membership     cluster
0  [TTG2014] 28378   GrG  218.055267  0.334857  0.111708         100  AGC 241936
Warning! Host of ZTF20actskcf is the hierarchical child of another object in Simbad, choosing parent as host instead...
               main_id otype         ra       dec      dist  membership                    cluster
0       [TKK2018] 6419   GrG  46.836240  4.427210  0.036473          75  Gaia DR2 3443605994326016
1  [T2015] nest 200252   GrG  46.882900  4.369400  0.052340         100  Gaia DR3 3443605994326016
2   [CHM2007] LDC  223   GrG  46.890417  4.335833  0.077927         100  Gaia DR2 3443605994326016
```

and now for the traceback:
```python
Traceback (most recent call last):
  File "/rcfs/projects/pinn4photoz/astroghost/example_script_idx0.py", line 40, in <module>
    hosts = getTransientHosts(snName, snCoord, snClass, verbose=True, starcut='gentle', ascentMatch=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/people/enge625/.conda/envs/new_astro/lib/python3.11/site-packages/astro_ghost/ghostHelperFunctions.py", line 687, in getTransientHosts
    tempHost3 = findNewHosts(transientName_remaining, snCoord_remaining, snClass_remaining, verbose, starcut, ascentMatch, px, savepath)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/people/enge625/.conda/envs/new_astro/lib/python3.11/site-packages/astro_ghost/ghostHelperFunctions.py", line 932, in findNewHosts
    host_DF = checkSimbadHierarchy(host_DF, verbose=verbose)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/people/enge625/.conda/envs/new_astro/lib/python3.11/site-packages/astro_ghost/ghostHelperFunctions.py", line 237, in checkSimbadHierarchy
    if ((not tap_pandas.empty) and (tap_pandas.loc[0, 'membership'] > 50)):
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/missing.pyx", line 388, in pandas._libs.missing.NAType.__bool__
TypeError: boolean value of NA is ambiguous
```

**Comment by alexandergagliano** [comment]
@awe2 I've just re-released the code catching this edge case (where an entry is found but with a hierarchical association probability is nan) - could you try again with a fresh install?

**Comment by awe2** [comment]
this doesn't repeat anymore, closing.
