### ISSUE TITLE
Expired certificate for astroconda causes getGHOST to fail.

### ISSUE THREAD

**Issue by patrickaleo** [uiucsn/astro_ghost#28]
On any new install or instance (where GHOST database hasn't been made yet) getGHOST function queries astroconda (specifically, https://astroconda.org/aux/vo_databases/conesearch_good.json), which has an expired certificate, causing the following traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/destry.saul/code/astro-ghost-scrap/venv/lib/python3.10/site-packages/astro_ghost/ghostHelperFunctions.py", line 15, in <module>
    from astro_ghost.PS1QueryFunctions import *
  File "/Users/destry.saul/code/astro-ghost-scrap/venv/lib/python3.10/site-packages/astro_ghost/PS1QueryFunctions.py", line 35, in <module>
    vos_catalog.list_catalogs("conesearch_good")
  File "/Users/destry.saul/code/astro-ghost-scrap/venv/lib/python3.10/site-packages/astroquery/vo_conesearch/vos_catalog.py", line 944, in list_catalogs
    return get_remote_catalog_db(service_type, cache=cache,
  File "/Users/destry.saul/code/astro-ghost-scrap/venv/lib/python3.10/site-packages/astroquery/vo_conesearch/vos_catalog.py", line 663, in get_remote_catalog_db
    return VOSDatabase.from_json(
  File "/Users/destry.saul/code/astro-ghost-scrap/venv/lib/python3.10/site-packages/astroquery/vo_conesearch/vos_catalog.py", line 524, in from_json
    with get_readable_fileobj(filename, **kwargs) as fd:
  File "/Users/destry.saul/.pyenv/versions/3.10.6/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/destry.saul/code/astro-ghost-scrap/venv/lib/python3.10/site-packages/astropy/utils/data.py", line 343, in get_readable_fileobj
    name_or_obj = download_file(
  File "/Users/destry.saul/code/astro-ghost-scrap/venv/lib/python3.10/site-packages/astropy/utils/data.py", line 1532, in download_file
    raise errors[sources[0]]
  File "/Users/destry.saul/code/astro-ghost-scrap/venv/lib/python3.10/site-packages/astropy/utils/data.py", line 1500, in download_file
    f_name = _download_file_from_source(
  File "/Users/destry.saul/code/astro-ghost-scrap/venv/lib/python3.10/site-packages/astropy/utils/data.py", line 1284, in _download_file_from_source
    with _try_url_open(
  File "/Users/destry.saul/code/astro-ghost-scrap/venv/lib/python3.10/site-packages/astropy/utils/data.py", line 1224, in _try_url_open
    raise urllib.error.URLError(msg)
urllib.error.URLError: <urlopen error Verification of TLS/SSL certificate at https://astroconda.org/aux/vo_databases/conesearch_good.json failed: this can mean either the server is misconfigured or your local root CA certificates are out-of-date; in the latter case this can usually be addressed by installing the Python package "certifi" (see the documentation for astropy.utils.data.download_url) or in both cases you can work around this by passing allow_insecure=True, but only if you understand the implications; the original error was: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>
```

According to astroconda website (https://astroconda.readthedocs.io/en/latest/), Astroconda is no longer supported by STScI. As such, I don't know if that certificate will ever be renewed. It is now recommended to use the `stenv` environment (https://stenv.readthedocs.io/en/latest/).

**Comment by alexandergagliano** [comment]
Looks like the offending line came from a now obsolete catalog lookup. I've cleaned things up a bit; let me know if you're still having the same problem!

**Comment by alexandergagliano** [comment]
@patrickaleo Closing due to inaction -- feel free to re-open if you run into this again.
