### ISSUE TITLE
Error in getTransientHosts when snName kwarg not specified

### ISSUE THREAD

**Issue by astrophpeter** [uiucsn/astro_ghost#5]
I wonder if you could help me understand the error I am getting. My goal is find details about a supernova host galaxy given the supernova position only. My understanding is that I can use getTransientHosts for this purpose and just specify the supernova coordinates?

Here is a minimum working example: 

```
from astro_ghost.ghostHelperFunctions import getTransientHosts, getGHOST
from astropy.coordinates import SkyCoord
supernova_position = SkyCoord(ra=10, dec=30, unit='deg')
getGHOST(real=False, verbose=0)
getTransientHosts(snCoord=[supernova_position], verbose=0, starcut='normal')
```

produces the following error:

```
Finding northern sources with Pan-starrs...
Traceback (most recent call last):
  File "XXX", line X, in <module>
    getTransientHosts(snCoord=[supernova_position], verbose=0, starcut='normal')
  File "XXX/lib/python3.9/site-packages/astro_ghost/ghostHelperFunctions.py", line 504, in getTransientHosts
    tempHost3 = findNewHosts(snName_remaining, snCoord_remaining, snClass_remaining, verbose, starcut, ascentMatch, px)
  File "XXX/lib/python3.9/site-packages/astro_ghost/ghostHelperFunctions.py", line 567, in findNewHosts
    transient_dict = {k.replace(' ', ''): v for k, v in transient_dict.items()}
  File "XXX/lib/python3.9/site-packages/astro_ghost/ghostHelperFunctions.py", line 567, in <dictcomp>
    transient_dict = {k.replace(' ', ''): v for k, v in transient_dict.items()}
AttributeError: 'float' object has no attribute 'replace'
```

whereas,

```
from astro_ghost.ghostHelperFunctions import getTransientHosts, getGHOST
from astropy.coordinates import SkyCoord

supernova_position = SkyCoord(ra=10, dec=30, unit='deg')
getGHOST(real=False, verbose=0)
getTransientHosts(snCoord=[supernova_position], snName=['I do not know the name'], verbose=0, starcut='normal')
```

seems to work fine, and does not throw an error. Is this expected behavior? 

From the stack, the problem is that k appears to be a float, `transient_dict = {str(k).replace(' ', ''): v for k, v in transient_dict.items()}` may be the fix? I checked what k actually is in may case for the code that throws the error, and it is nan?

Best,
Peter

**Comment by alexandergagliano** [comment]
@astrophpeter Good find! I've just pushed a fix that will allow you to associate transients with hosts even without giving a name.
