### ISSUE TITLE
Cannot import astro_ghost library

### ISSUE THREAD

**Issue by fforster** [uiucsn/astro_ghost#6]
After running python setup.py install and trying to import the library I get:

```(base) fforster@fforster-XPS-13-9310:~/Dropbox/Work/astro_ghost$ python
Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import astro_ghost
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fforster/Dropbox/Work/astro_ghost/astro_ghost/__init__.py", line 3, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'astro_ghost.version'```

**Comment by alexandergagliano** [comment]
@fforster I've just updated both the repo and the pypi distribution with version 0.1.35, where I don't see this issue. I'll close this issue, but I'm happy to re-open it if you're still having this problem. Congrats again on the DELIGHT paper!
